name: Build OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3 python3-pip rsync unzip zlib1g-dev file wget
        python3 -m pip install setuptools

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/lede/tmp
          ~/lede/staging_dir
        key: ${{ runner.os }}-lede-${{ hashFiles('**/.config') }}
        restore-keys: |
          ${{ runner.os }}-lede-

    - name: Load .config
      run: |
        cp .config ./lede/.config

    - name: Update feeds
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build firmware
      run: |
        cd lede
        make defconfig
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: LEDE-Firmware
        path: lede/bin/targets/
