name: Build OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Clone LEDE source
        run: |
          git clone https://github.com/coolsnowwolf/lede ./
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load custom config
        run: |
          cp .config build/.config || true
          [ -f ".config" ] && echo "Using custom config"

      - name: Download package sources
        run: |
          make defconfig
          make download -j8

      - name: Build firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt-K2P-A2
          path: bin/targets/
