name: Build OpenWrt for K2P A2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: |
          ~/work/OpenWrt/build_dir
          ~/work/OpenWrt/staging_dir
        key: ${{ runner.os }}-openwrt-${{ hashFiles('**/.config') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ \
          gawk gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python3 unzip wget zlib1g-dev python3-distutils

    - name: Load custom .config
      run: |
        cp .config build/.config || true

    - name: Make download
      run: |
        make defconfig
        make download -j8

    - name: Compile firmware
      run: |
        make -j$(nproc) || make -j1 V=s

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt-K2P-Firmware
        path: bin/targets/
